// Code generated by github.com/sicuni/go-generate.

package model

const TableNameUser = "user"

// User mapped from table &lt;user>
type User struct {
	Id       int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:false" json:"id"`
	UserName string `gorm:"column:user_name;type:varchar(20);not null" json:"user_name"`
}

// TableName User's table name
func (u *User) TableName() string {
	return TableNameUser
}
